### ISSUE TITLE
No action triggered after positive button is pressed

### ISSUE THREAD

**Issue by ernstmul** [MSF-Jarvis/AppRate#6]
When using the following snippet:
`new AppRate(this)
	.init();`

The dialog does show, however after clicking the 'Rate it!' button, nothing happens.

**Comment by MSF-Jarvis** [comment]
Fixed in master

**Comment by smsapiro21** [comment]
I still have this issue. Could you please help me out? I only see a "develop" and an "example-app" branch, no "master."
